config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'activities#index'

  resource :session
  resources :users, only: %i[new create]
  resources :passwords, param: :token
  resource :verify_email_address, only: %i[show], param: :token do
    post :resend
  end

  resources :activities, only: %i[index create destroy] do
    collection do
      get 'random'
      get 'suggestion'
    end
  end
end

app/models/activity.rb
# frozen_string_literal: true

# An Activity that a user could do instead of watching TV
class Activity < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/email_address_verification.rb
# frozen_string_literal: true

# Verify a user's email address with a token that can be sent in an email and used to find the user
module EmailAddressVerification
  extend ActiveSupport::Concern

  TOKEN_EXPIRES_IN = 24.hours
  UNVERIFIED_GRACE_PERIOD = 7.days

  included do
    generates_token_for :email_address_verification, expires_in: TOKEN_EXPIRES_IN

    after_commit :require_email_address_verification, if: :requires_email_verification?, on: %i[create update]

    scope :still_unverified_after_grace_period, lambda {
      where(verified_at: nil)
        .where(created_at: ...UNVERIFIED_GRACE_PERIOD.ago)
        .includes(:activities)
    }
  end

  def email_address_verification_token
    generate_token_for(:email_address_verification)
  end

  def verify!
    return false if verification_expired? || verified?

    update!(verified_at: Time.current)
  end

  def verified?
    verified_at.present?
  end

  def unverified?
    verified_at.nil?
  end

  def verification_expired?
    return false unless verification_sent_at

    expires_at = verification_sent_at + EmailAddressVerification::TOKEN_EXPIRES_IN
    Time.current > expires_at
  end

  private

  def requires_email_verification?
    !skip_email_verification && new_user_or_email_address_updated?
  end

  def new_user_or_email_address_updated?
    !persisted? || saved_change_to_email_address?
  end

  def require_email_address_verification
    return unless persisted?

    # Use update_column because this runs inside after_commit
    update_column(:verified_at, nil) # rubocop:disable Rails/SkipsModelValidations
    UserMailer.verify_email_address(self).deliver_later!
  end
end

app/controllers/activities_controller.rb
# frozen_string_literal: true

# Activities Controller
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[destroy]
  before_action :set_activities, only: %i[index random]

  # GET /activities
  def index
    @activity = Activity.new
  end

  # POST /activities
  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user

    if @activity.save
      redirect_to activities_path, notice: 'Activity created!' # rubocop:disable Rails/I18nLocaleTexts
    else
      render :index, status: :unprocessable_content
    end
  end

  # DELETE /activities/1
  def destroy
    @activity.destroy!
    redirect_to activities_path, notice: 'Activity deleted!', status: :see_other # rubocop:disable Rails/I18nLocaleTexts
  end

  # GET /activities/random
  def random
    @activity = Activity.new
    @random_activity = @activities.sample
    render :index
  end

  # GET /activities/suggestion
  def suggestion
    @activity = Activity.new
    @random_activity = Activity.new(name: ACTIVITIES_LIST.sample)
    render :index
  end

  private

  def set_activity
    @activity = Activity.find(params.expect(:id))
  end

  def set_activities
    @activities = current_user.activities
  end

  def activity_params
    params.expect(activity: [:name])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
# frozen_string_literal: true

# User authentication
module Authentication
  extend ActiveSupport::Concern
  include ActionView::Helpers::DateHelper

  included do
    before_action :require_authentication
    before_action :update_session_last_seen_at_and_expires_at, if: :user_signed_in?
    before_action :warn_of_impeding_account_deletion, if: :user_email_address_unverified?

    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
      skip_before_action :update_session_last_seen_at_and_expires_at, **options
    end
  end

  private

  def user_signed_in?
    Current.user.present?
  end

  def authenticated?
    resume_session
  end

  def require_authentication
    resume_session || request_authentication
  end

  def resume_session
    session = find_session_by_cookie
    return false unless session

    if session.expires_at <= Time.zone.now
      session.destroy
      return false
    end

    Current.session = session
  end

  def find_session_by_cookie
    Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
  end

  def request_authentication
    session[:return_to_after_authenticating] = request.url

    respond_to do |format|
      format.html { redirect_to new_session_path }
      format.turbo_stream { head :unauthorized } # prevents redirect
    end
  end

  def after_authentication_url
    session.delete(:return_to_after_authenticating) || root_url
  end

  def start_new_session_for(user)
    create_session(user).tap do |session|
      Current.session = session
      cookies.signed.permanent[:session_id] = {
        value: session.id,
        httponly: true,
        same_site: :lax
      }
    end
  end

  def create_session(user)
    user.sessions.create!(
      user_agent: request.user_agent,
      ip_address: request.remote_ip,
      last_seen_at: Time.zone.now,
      expires_at: 2.weeks.from_now
    )
  end

  def terminate_session
    Current.session&.destroy
    cookies.delete(:session_id)
  end

  def update_session_last_seen_at_and_expires_at
    return unless Current.session

    # Using update_columns is faster when there's no need to run validations
    Current.session.update_columns( # rubocop:disable Rails/SkipsModelValidations
      last_seen_at: Time.current,
      expires_at: 2.weeks.from_now
    )
  end

  def warn_of_impeding_account_deletion
    if Current.user.verification_expired?
      active_for = Time.current - Current.user.created_at
      grace_remaining = [EmailAddressVerification::UNVERIFIED_GRACE_PERIOD - active_for, 0].max
      timeframe = distance_of_time_in_words(grace_remaining)
      flash[:warn] = "This account will be deleted unless you verify your email address within #{timeframe}"
    else
      flash[:warn] = 'Please verify your email address' # rubocop:disable Rails/I18nLocaleTexts
    end
  end

  def user_email_address_unverified?
    Current.user&.unverified?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def random_cta
    CALL_TO_ACTION_PHRASES.sample
  end

  def random_activity
    ACTIVITIES_LIST.sample
  end
end

app/views/activities/_activity.html.erb
<li id="<%= dom_id activity %>">
  <article class="activity">
    <span class="activity-name">
      <%= activity.name.capitalize %>
    </span>

    <span class="activity-actions">
      <%= button_to "Delete",
        activity,
        method: :delete,
        class: "secondary outline",
        form: { data: { turbo_confirm: "Remove this activity?" } } %>
    </span>
  </article>
</li>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <article class="flash flash-error">
      <strong>
        <%= pluralize(activity.errors.count, "error") %> prevented this activity from being saved:
      </strong>
      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </article>
  <% end %>

  <fieldset role="group">
    <%= form.text_field :name,
          placeholder: "Going to the gym, reading a book…",
          aria: { label: "Activity name" } %>

    <%= form.submit "Add to your list" %>
  </fieldset>
<% end %>

app/views/activities/index.html.erb
<% content_for :title, "Stop Scrolling" %>

<% flash.each do |type, message| %>
  <% alert_class = case type.to_sym
     when :notice then "flash flash-success"
     when :alert  then "flash flash-error"
     else "flash flash-error"
     end %>

  <aside role="status" class="<%= alert_class %>">
    <%= message %>
  </aside>
<% end %>

<section class="intro">
  <h1>Stop scrolling!</h1>
  <p>
    Ever catch yourself endlessly scrolling, wishing you were doing something more meaningful, but can’t decide what?
  </p>
</section>

<section class="random">
  <article>
    <h2>Get off your phone and do something else.</h2>
    <% if @random_activity %>
      <p>
        <%= random_cta %> <strong><%= @random_activity.name.downcase %></strong>.
      </p>
    <% elsif @activities.blank? %>
      <p>Add some activities to get inspired.</p>
    <% else %>
      <p>Need some inspiration?</p>
    <% end %>

    <%= link_to "From your list",
                random_activities_path,
                role: "button",
                data: { turbo: false },
                aria: { label: "From your list" } %>

    <%= link_to "Random suggestion",
                suggestion_activities_path,
                role: "button",
                class: 'secondary',
                data: { turbo: false },
                aria: { label: "Random suggestion" } %>
  </article>
</section>

<section class="add-activity">
  <article>
    <h2>What do you like doing?</h2>
    <p>What do you wish you were doing more of?</p>
    <%= render "form", activity: @activity %>
  </article>
</section>

<section class="activities">
  <h2>Things you like doing.</h2>

  <% if @activities.present? %>
    <ul class="activity-list">
      <%= render @activities %>
    </ul>
  <% else %>
    <p class="empty-state">
      Nothing here yet. Add your first activity above.
    </p>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Stop Scrolling" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "pico.min", data: { turbo_track: "reload" } %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="container">
      <nav>
        <ul>
          <li>
            <strong>
              <%= link_to 'stopscroll.ing', root_path %>
            </strong>
          </li>
        </ul>
        <ul>
          <% if Current.session %>
            <details class="dropdown">
              <summary>
                <small><%= current_user.email_address %></small>
              </summary>
              <ul dir="rtl">
                <% if current_user.unverified? %>
                  <li>
                    <%= button_to 'Resend verification email',
                            resend_verify_email_address_path,
                            data: { turbo: false },
                            aria: { label: "Resend verification email" } %>
                  </li>
                <% end %>
                <li>
                  <%= button_to 'Sign out', session_path, method: :delete, class: "secondary outline" %>
                </li>
              </ul>
            </details>
          <% else %>
            <div>
              <li><%= link_to 'Sign up', new_user_path  %></li>
              <li><%= link_to 'Sign in', new_session_path, role: "button"  %></li>
            </div>
          <% end %>
        </ul>
      </nav>
    </header>

    <main class="container">
      <%= yield %>
    </main>

    <footer class="container">
      <small>
        A tiny reminder that boredom is an opportunity.
      </small>
    </footer>
  </body>
</html>